import os
from pathlib import Path
from typing import Iterable

import cv2
import deeplabcut
import numpy as np
import pandas as pd
from deeplabcut.utils import auxfun_multianimal
from tqdm import tqdm


def remove_filtered_prediction_files(
    config: str,
    video: str | Iterable[str],
    shuffle: int,
    destfolder: str | None,
    trainingsetindex: int = 0,
    modelprefix: str = "",
    track_method: str = "",
    remove_csv: bool = True,
) -> list[str]:
    """Delete files generated by ``deeplabcut.filterpredictions``.

    Returns the absolute paths that were removed.
    """
    cfg = deeplabcut.auxiliaryfunctions.read_config(config)
    track_method = auxfun_multianimal.get_track_method(cfg, track_method=track_method)

    dlc_scorer, _ = deeplabcut.auxiliaryfunctions.get_scorer_name(
        cfg,
        shuffle,
        trainFraction=cfg["TrainingFraction"][trainingsetindex],
        modelprefix=modelprefix,
    )

    videos = deeplabcut.auxiliaryfunctions.get_list_of_videos(video, "")
    removed_paths: list[str] = []

    for video in videos:
        current_dest = destfolder or str(Path(video).parent)
        vname = Path(video).stem

        try:
            _, filtered_path, _, _ = deeplabcut.auxiliaryfunctions.load_analyzed_data(
                current_dest,
                vname,
                dlc_scorer,
                filtered=True,
                track_method=track_method,
            )
        except FileNotFoundError:
            continue

        filtered_path = os.path.abspath(filtered_path)
        if os.path.exists(filtered_path):
            os.remove(filtered_path)
            removed_paths.append(filtered_path)

        if remove_csv:
            csv_path = filtered_path.replace(".h5", ".csv")
            if os.path.exists(csv_path):
                os.remove(csv_path)
                removed_paths.append(csv_path)

    return removed_paths

